/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import EstructuraLogica.Arbol;
import com.sun.xml.internal.txw2.TXW;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Carlollos
 */
public class FribonaciRecursivo extends javax.swing.JFrame {

       public static Arbol objArbol = new Arbol();
       public static Lienzo objLienzo = new Lienzo();
        public static Controlador objControlador = new Controlador(objLienzo, objArbol);
        
        public static ArrayList lista = new ArrayList();
        public static int cont = 0;
        
   
    /**
     * Creates new form FribonaciRecursivo
     */
    public FribonaciRecursivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFibo = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResul = new javax.swing.JTextArea();
        labelresul = new javax.swing.JLabel();
        labelResul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Fibonacci Recursivo");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tamaño de la serie fibonaci");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txaResul.setColumns(20);
        txaResul.setRows(5);
        jScrollPane1.setViewportView(txaResul);

        labelresul.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelresul.setText("El ultimo numero de la sucecion fibonaci de tamaño es");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtFibo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerar)
                        .addGap(52, 52, 52)
                        .addComponent(labelresul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelResul, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar)
                    .addComponent(labelresul)
                    .addComponent(labelResul, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
   
    
       txaResul.setText("");
       int SerieFibo = CalcularFibonacci(Integer.parseInt(txtFibo.getText()));
       labelresul.setText("El ultimo numero de la sucecion fibonaci de tamaño "+txtFibo.getText()+" es --->");
       labelResul.setText(Integer.toString(SerieFibo));
       
        for (int i = 0; i < Integer.parseInt(txtFibo.getText()); i++) {
            txaResul.setText(txaResul.getText()+"  "+CalcularFibonacci(i));
        }
        
       
        objControlador.Iniciar();
        
        JFrame ventana = new JFrame();
        ventana.getContentPane().add(objLienzo);
        ventana.setDefaultCloseOperation(3);
        ventana.setSize(600,600);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    
     public static int CalcularFibonacci(int numero){
         
            //Se establece el caso base de la serie Fibonacci que es 0 y 1 sus primeros 2 dijitos 
         if(numero == 0){
             return 0;
         }else{
            if(numero == 0 || numero == 1){
                //En caso de que sea cumpla la condicion de regresa un 1
                
                return 1;
            }else{
                //En caso contrario se ejecuta una doble recursividad
                
                return CalcularFibonacci(numero - 1) + CalcularFibonacci(numero - 2);
            }
            }
        }
     
     public static int CalcularFibonacciTexto(int numero){
            //Se establece el caso base de la serie Fibonacci que es 0 y 1 sus primeros 2 dijitos 
         if(numero == 0){
             return 0;
         }else{
            if(numero == 0 || numero == 1){
                //En caso de que sea cumpla la condicion de regresa un 1
                 
                return 1;
            }else{
                //En caso contrario se ejecuta una doble recursividad
              
                return CalcularFibonacciTexto(numero - 1) + CalcularFibonacciTexto(numero - 2);
            }
            }
        }
       
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FribonaciRecursivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FribonaciRecursivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FribonaciRecursivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FribonaciRecursivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FribonaciRecursivo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelResul;
    private javax.swing.JLabel labelresul;
    private javax.swing.JTextArea txaResul;
    private javax.swing.JTextField txtFibo;
    // End of variables declaration//GEN-END:variables
}
